### ISSUE TITLE
dealing with other angular modules installed with bower

### ISSUE THREAD

**Issue by gbozee** [stackfull/angular-webpack-plugin#19]
Webpack doesn't seem to find third party angularjs modules. Here is my webpack.config.js

    var AngularPlugin = require('angular-webpack-plugin');
    var path = require('path');
    var bowerRooot = __dirname+"bower_components"; 
    module.exports = {
            entry:"./app.js",
	    output:{
		path:__dirname,
		filename:"bundle.js"
	    },
	module:{
		loaders:[
			{test: /\.css$/,loader:"style!css"},
			{test:/\.json$/,loader:"json"},
			// {test:/\.html$/,loader:"html"},

		]
	},
	resolve:{
		root:[process.cwd(),path.resolve('bower_components/')],
		// root:[process.cwd())],
		extensions: ['','.js'],
	},
	plugins:[new AngularPlugin()],
	externals:{
		// "angular":"angular"
       	}
    }

When i have angular-ui-bootstrap installed with bower and in my `app.js` I have this

    var myApp = angular.module('myApp', ['ui-bootstrap',]);

webpack throws this error

    ERROR in ./app.js
    Module not found: Error: Cannot resolve module 'ui-bootstrap' in F:\work-project
    s\python\django-projects\MultipleDatePicker
     @ ./app.js

**Comment by stackfull** [comment]
I think ui-bootstrap is in the "angular-bootstrap" bower package. So you'll have to put an `alias` in the `module` section of your config. Something like `{ 'ui-bootstrap$': 'angular-bootstrap' }`.

**Comment by gbozee** [comment]
Thanks. solved the issue

**Comment by stackfull** [comment]
think this is closed
