### ISSUE TITLE
Require ui.bootstrap (webpackMissingModule)

### ISSUE THREAD

**Issue by Asgator** [stackfull/angular-webpack-plugin#20]
Why "Cannot find module"?
ui.bootstrap - http://angular-ui.github.io/bootstrap/

## bundle.js
`__webpack_require__(!(function webpackMissingModule() { throw new Error("Cannot find module \"template/modal/window.html\""); }()));`
	`__webpack_require__(!(function webpackMissingModule() { throw new Error("Cannot find module \"template/tabs/tabset.html\""); }()));`
	`__webpack_require__(!(function webpackMissingModule() { throw new Error("Cannot find module \"ui.bootstrap.tpls\""); }()))`

## app.js
`"use strict";`

`angular`
  `.module('app', [`
    `'ui.router',` 
    `'ui.bootstrap',`
  `]);`
## webpack.config.js

      `'ui.router$': path.resolve(__dirname, 'www/static/bower_components/angular-ui-router/release/angular-ui-router.js'),`
      `'ui.bootstrap$': path.resolve(__dirname, 'www/static/bower_components/angular-ui-bootstrap-bower/ui-bootstrap-tpls.js')`

**Comment by stackfull** [comment]
I think it's down to the way ui.bootstrap is packaged. Webpack has an option to not parse certain files http://webpack.github.io/docs/configuration.html#module-noparse which you can point at the bower file.

The recommended way to use webpack is to try to use an npm module first to avoid packaging issues. Angular modules aren't often good npm modules though, so second best is to use bower and try to target the least packaged option (un-minified, un-bundled) - so you could try the non "-tpls" version. But my experience is that the bower components are usually too hard to deal with, so I just shim them with `noParse` and then deal with the inevitable loss of dependency information. It's a shame, and I'm open to suggestions.

**Comment by Asgator** [comment]
Thank you for your help.

We decided yet to do so, temporarily)

`module: {
   noParse: [
         /bower_components/
    ]
  },`

**Comment by danawhite** [comment]
I'm currently dealing with the same issue. Where in webpack.config.js did you add 'ui.router' and 'ui.bootstrap'?

**Comment by Asgator** [comment]
We remove Angular and take ReactJs, for Webpack and Angular it terribly inconvenient. Sorry, i don't know how help you.
