### ISSUE TITLE
a webpack loader that gets rid of the angular module system

### ISSUE THREAD

**Issue by mkoryak** [stackfull/angular-webpack-plugin#27]
Not really an issue, but figured I could direct some people to a non-abandoned project that solves this problem but in an opposite way.

instead of using angular's broken dependency system, i remove it completely and use require instead. 
everything just magically works. 
 
https://www.npmjs.com/package/remove-angular-modules-loader

**Comment by stackfull** [comment]
Interesting approach.

Linked it from the README
